In [1]:
import torch
import numpy as np

In [2]:
L, N, Hin, Hout = 4, 3, 2, 5
n_rnns = 1
rnn = torch.nn.RNN(Hin, Hout, n_rnns, batch_first=True)

In [3]:
x = torch.randn(N, L, Hin)
h0 = torch.randn(n_rnns, N, Hout)

In [4]:
test = rnn(x,h0)

In [5]:
t1,t2 = test

In [6]:
t1.shape, t2.shape

(torch.Size([3, 4, 5]), torch.Size([1, 3, 5]))

In [7]:
t1[:,3] == t2

tensor([[[True, True, True, True, True],
         [True, True, True, True, True],
         [True, True, True, True, True]]])

In [8]:
torch.tensor(np.array(10)).numpy()

array(10)

In [2]:
import sys
sys.path.append("../src") if "../src" not in sys.path else None # avoid adding multiple relave paths to sys.path
from methods import *

In [3]:
Dataset()

In [16]:
# TORCH CROSS ENTROPY DOES NOT SUPPORT "MULTI TARGET" - i.e. true cross-entropy
X, label = torch.ones((1,2)), torch.ones(1,dtype=torch.int64)
#label[0,0] = 0
print(label)
X[0,0] = 0
print(X)
torch.nn.functional.cross_entropy(input=X, target=label)

tensor([1])
tensor([[0., 1.]])


tensor(0.3133)

In [17]:
W = torch.nn.Linear(2,3).weight

In [24]:
W.size(1)

2

In [1]:
def f(x):
    return 2

g = f

In [ ]:
g(

In [10]:
x = torch.randn(5)

In [91]:
a, b = torch.randn(2, requires_grad=True), torch.randn(1, requires_grad=False)
a,b

(tensor([-0.7600,  0.7474], requires_grad=True), tensor([0.8973]))

In [92]:
Q = torch.sum(a**2 * b)

In [84]:
external_grad = torch.tensor(1.)
external_grad

tensor(1.)

In [85]:
Q.backward(gradient=external_grad)

In [86]:
external_grad

tensor(1.)

In [87]:
a.grad

tensor([-1.5978,  3.3204])

In [88]:
a

tensor([-0.7915,  1.6447], requires_grad=True)

In [89]:
b

tensor([1.0094])

In [90]:
a = torch.tensor([2., 3.], requires_grad=True)
b = torch.tensor([6., 4.], requires_grad=True)
Q = 3*a**3 - b**2
external_grad = torch.tensor([1., 1.])
Q.backward(gradient=external_grad)
external_grad

tensor([1., 1.])

In [96]:
type(b) == torch.Tensor

True

In [138]:
x = torch.randn((5,4,3))
values, idxs = torch.topk(x, k=2, dim=-1)

In [139]:
values.shape, idxs.shape

(torch.Size([5, 4, 2]), torch.Size([5, 4, 2]))

In [148]:
torch.gather(x, -1, idxs).shape

torch.Size([5, 4, 2])

In [154]:
def f(**kwargs):
    print(kwargs, type(kwargs))

d = {'a': 2, 'b': 3}
f(**d)

{'a': 2, 'b': 3} <class 'dict'>
