In [17]:
import torch
import numpy as np

In [34]:
L, N, Hin, Hout = 4, 3, 2, 5
n_rnns = 1
rnn = torch.nn.RNN(Hin, Hout, n_rnns, batch_first=True)

In [35]:
x = torch.randn(N, L, Hin)
h0 = torch.randn(n_rnns, N, Hout)
print(x.shape, h0.shape)

torch.Size([3, 4, 2]) torch.Size([1, 3, 5])


In [36]:
test = rnn(x,h0)

In [37]:
test[0].shape, test[1].shape

(torch.Size([3, 4, 5]), torch.Size([1, 3, 5]))

In [ ]:
test

In [5]:
t1,t2 = test

In [6]:
t1.shape, t2.shape

(torch.Size([3, 4, 5]), torch.Size([1, 3, 5]))

In [7]:
t1[:,3] == t2

tensor([[[True, True, True, True, True],
         [True, True, True, True, True],
         [True, True, True, True, True]]])

In [8]:
torch.tensor(np.array(10)).numpy()

array(10)

In [2]:
import sys
sys.path.append("../src") if "../src" not in sys.path else None # avoid adding multiple relave paths to sys.path
from methods import *

In [3]:
Dataset()

In [16]:
# TORCH CROSS ENTROPY DOES NOT SUPPORT "MULTI TARGET" - i.e. true cross-entropy
X, label = torch.ones((1,2)), torch.ones(1,dtype=torch.int64)
#label[0,0] = 0
print(label)
X[0,0] = 0
print(X)
torch.nn.functional.cross_entropy(input=X, target=label)

tensor([1])
tensor([[0., 1.]])


tensor(0.3133)

In [17]:
W = torch.nn.Linear(2,3).weight

In [24]:
W.size(1)

2

In [1]:
def f(x):
    return 2

g = f

In [ ]:
g(

In [10]:
x = torch.randn(5)

In [91]:
a, b = torch.randn(2, requires_grad=True), torch.randn(1, requires_grad=False)
a,b

(tensor([-0.7600,  0.7474], requires_grad=True), tensor([0.8973]))

In [92]:
Q = torch.sum(a**2 * b)

In [84]:
external_grad = torch.tensor(1.)
external_grad

tensor(1.)

In [85]:
Q.backward(gradient=external_grad)

In [86]:
external_grad

tensor(1.)

In [87]:
a.grad

tensor([-1.5978,  3.3204])

In [88]:
a

tensor([-0.7915,  1.6447], requires_grad=True)

In [89]:
b

tensor([1.0094])

In [90]:
a = torch.tensor([2., 3.], requires_grad=True)
b = torch.tensor([6., 4.], requires_grad=True)
Q = 3*a**3 - b**2
external_grad = torch.tensor([1., 1.])
Q.backward(gradient=external_grad)
external_grad

tensor([1., 1.])

In [96]:
type(b) == torch.Tensor

True

In [138]:
x = torch.randn((5,4,3))
values, idxs = torch.topk(x, k=2, dim=-1)

In [139]:
values.shape, idxs.shape

(torch.Size([5, 4, 2]), torch.Size([5, 4, 2]))

In [148]:
torch.gather(x, -1, idxs).shape

torch.Size([5, 4, 2])

In [66]:
def f(a, **kwargs):
    print(a)
    print(kwargs, type(kwargs))

d = {'a': 2, 'b': 3, 'c':4}
f(**d)

2
{'b': 3, 'c': 4} <class 'dict'>


In [ ]:
def 

In [65]:
X,Y = torch.randn((10,2)), torch.randn((5,2))
mandists = torch.sum((X[:,None]-Y[None])**2, axis=-1)
print((X[:,None]-Y[None]).shape, mandists.shape)

torch.Size([10, 5, 2]) torch.Size([10, 5])


In [ ]:
[10,1,2] + [1,5,2] => [10,5,2]

In [50]:
dists = torch.cdist(X,Y,compute_mode='use_mm_for_euclid_dist')

In [52]:
mandists

tensor([[4.1127e+00, 9.3647e+00, 1.0746e+00, 4.4152e-01, 5.6463e+00],
        [5.6894e+00, 8.7903e+00, 2.3298e+00, 3.7816e+00, 1.0156e+00],
        [2.4815e+00, 6.7801e+00, 3.8200e-01, 1.0728e-02, 3.1811e+00],
        [3.3088e+00, 7.7801e+00, 2.5535e+00, 1.2073e+00, 6.8445e+00],
        [2.7053e-01, 2.0636e+00, 1.9724e+00, 1.4716e+00, 1.1450e+00],
        [6.6821e-01, 3.3748e+00, 1.8501e+00, 8.6606e-01, 3.0146e+00],
        [2.4013e+00, 8.3213e-01, 1.1653e+01, 9.4784e+00, 7.8536e+00],
        [8.1488e-01, 3.6932e+00, 1.0105e+00, 4.7989e-01, 1.8623e+00],
        [1.2363e+00, 3.5936e+00, 1.1402e+00, 1.2455e+00, 4.0108e-01],
        [3.1170e-01, 2.2498e+00, 3.0116e+00, 1.7721e+00, 3.3362e+00]])

In [53]:
dists

tensor([[2.0280, 3.0602, 1.0366, 0.6645, 2.3762],
        [2.3852, 2.9648, 1.5264, 1.9446, 1.0078],
        [1.5753, 2.6039, 0.6181, 0.1036, 1.7836],
        [1.8190, 2.7893, 1.5980, 1.0988, 2.6162],
        [0.5201, 1.4365, 1.4044, 1.2131, 1.0700],
        [0.8174, 1.8371, 1.3602, 0.9306, 1.7363],
        [1.5496, 0.9122, 3.4137, 3.0787, 2.8024],
        [0.9027, 1.9218, 1.0052, 0.6927, 1.3647],
        [1.1119, 1.8957, 1.0678, 1.1160, 0.6333],
        [0.5583, 1.4999, 1.7354, 1.3312, 1.8265]])

In [69]:
def g(a,b, **kwargs):
    print(a,b)
    print(kwargs)

kwargs = {'a': 2, 'b':3, 'c': 4}
g(**kwargs)

2 3
{'c': 4}


In [ ]:
f = g